### ISSUE TITLE
Roadmap version v0.4.0

### ISSUE THREAD

**Issue by stephanmg** [stephanmg/calorimetry#65]
TODOs:

(latest version working and tested by martin, 9a1e420c2b40197a7ab1042a589fd3b25b6e836c, but issues for Tabea remain?)
- [x] test version v0.3.13 again, then implement new features.

New Features:
<details>
<summary>version 0.3.15 </summary>

discuss with Martin:
- [x] add `lme_model` from Raw panel to all other panels as well
- [x] add statistics panel from Raw for 2-way ANCOVA to other panels as well (full summary table!) using function 
 
implement this too:
</details>

Old features:
<details>
<summary>version 0.3.14</summary>

- [x] `style_plot` from Raw panel needs to be added to all other panels in `server.R`.
`generate_statistical_table` 
- [x] bug fix release, address some TODOs in code. final version before tackling major tasks for v0.4.0
- [x] add pdf export output for all other panels, EE, TEE, RMR, Day Night Activity

</details>

<details>
<summary>Implemented in prior versions</summary>

<details>
<summary>for version 0.3.12</summary>
- [x] Rename HP and HP2 to Heldmaier 1 and Heldmaier 2 -> reveals HP and HP2 bug which is also on server, see issue stephanmg/calorimetry#72 
</details>

<details>
<summary>for version 0.3.13</summary>
- [x] BodyComposition pnale: lean, fat, body weight 3-way anova mit sex, diet, genotype mit ANOVA
- [x] check homogenity of regression slopes
- [x] nur heldmaieer eien formel
- [x] zeitgeber zeit in stunden bei rmr
- [x] day night nicht angezeigt in rmr gelb + dunkel
- [x] discussion: RER in tse files an issue, sometimes correct sometimes now... even for UCP1KO data set, override or 
</details>
- [x] test version v0.3.11,
- [x] test versions v0.3.12, v0.3.13 seems buggy already ... and then deploy to servers -> bad commit: from dd81ba65670fed4f267f6fecb7dabdd332ec174d to 8924e2d75fbac57b583abef28eb587085031bc09
- [x] add export functions to also save TEE, EE, and RMR (enhance do_export_all_data)
- [x] fix light cycle annotation Night only
- [x] Raw measurement: Basic plot add plotting control to autoscale or manually scale the plot
- [x] in-depth code review
- [x] RMR, TEE, DayNightActivity need to use zeitgeber time to select full days and day night (see example in other panels)
- [x] Light cycle annotation is not correctly shifted in example panels for above, correct this in all panels! also DAy Night selection need to use offset in case we do not filter for full days (light_on to light_on) - Day night should already work
- [x] more defensive metadata read-in (server seems to be more strict for null vectors as locally) 
- [x] metadatan von tse daten schöner darstellen in UI
- [x] add anova to statistics panel
- [x] rework export function (javascript) for pdf, and add svg pdf exprot everywhere
- [x] plotly bug for geom_bar in summary statistics RMR... -> done, but need to cleanup code!
- [x] Datetime format must be  "%d/%m/%Y %H:%M"  currently but there is also  "%d/%m/%Y %H:%M:%S" (with seconds)
 --> bug in get_time_diff function to get interval length listss, interval lengths reported wrongly... Phenomaster v8
- [x] EE -> day/night auswahl benötigt
- [x] make metadata read-in more robust, by allowing missing sections...
- [x] print list of offending highly varying values below the plot -> done, next  remove points interactively (bars toggle outlires), see chat code -> chat sublime editor
- [x] lasso select with mouse drawing a rectangle to select points in app -> chat sublime editor -> if points have been removed, either do a click("plotting") in the app to ensure points have been updates everywhere, or check if reactive val already has had this effect, same for first point with bars above
- [x] download dataframe from each plot (finalC1), add button to plotly button bar and get finalC1 stored in getSession and download as zipped datafile statistics und finalC1
- [x] test sable system file and COSMED again without metadata
- [x] graz datensatz testen
- [x] supress error messages -> `req`.
- [x] remove conditional error messages
- [x] relax failrue if columns missing in metadata sheet -> also need to be careful when NAs encountered, print shiny warning!
- [x] ronja und tabea datensätze testen
- [x] coarsening of data sets -> TEE effekte testen
- [x] remove 0 values, z-scale to remove outliers, 1l o2 consumption on average 20.40 kcal (RQ dependent) 
- [x] add metadata to every panel
</details>
