### ISSUE TITLE
Roadmap for version v0.2.0 and v0.1.0

### ISSUE THREAD

**Issue by stephanmg** [stephanmg/calorimetry#69]
-----------------------
~First of all, fix Datensätze K1, K2, K3, K4.~
fixed (version v0.2.0):
- [x] tests without metadata sheets as well (FIXMEs in code -> add statistics panel everywhere)
- [x] cleanup code and tidy up
- [x] very important, review zeitgeber zeit!
- [x] very important, review RMR with MK! and myself code review
- [x] multi-user support with global_data and avoid temporary disk files
- [x] skalierung x-achse und y-achse variabel halten
- [x] fix unique day count in RMR comparison non-RMR vs RMR
- [x] Day/Night selection does not work?
- [x] bei EE: select facet animals stimmt der plot nicht   
- [x] bug sick sample removal see MK screenshots
- [x] Verify TEE with MK - done scalefactor wrong need to divide by 60 not multiply
- [x] calculate time interval of 12 hours by start-end of light cycle in zeitgeber zeit?
- [x] plausibility checks for TEE: is lean and fat mass correctcly assigned? calculate TEE with lean mass, there should be no negative corelation... use dataframe after total energy expenditure has been calculated - seems correct
- [x] Add Zeitgeberzeit to other panels as well (EnergyExpenditure exmaple panel) - includes selection of Days and Animals
- [x] Add 2-covariates panels to others as well (TotalEnergyExpdentireu example panel) -TEE includes also example for full days only
- [x] debug TEE facets not working if grouped with zeitgeber zeit and DayCount factor
- [x] cleanup ANCOVA module,  full statistic for 2way ANCOVAs, generalize to > 2 covariates
- [x] add second covariate in ancova model
- [x] ANCOVA: specify which model used, verbunden or nicht-verbundene ANCOVA (dropdown menu to select: Days+Genotype verbunden! not independent)
- [x] select  full days only does not work
- [x] Plots by facets: Timeline auch coloren.
- [x] TEE: add individual data points to violin plot, no day numbers
- [x] Correct all equations, then display only HP Weir Anf Ferranini (excel sheet martin)
- [x] metadata: read-in gender from metadata sheet
- [x] Zeitgeber Zeit
- [x] Should we also add plots of test assumptions (visualizations), instead of only p-values from Levene/Shapiro tests?
- [x] add 3-way ANCOVA for DayNight for instance?
- [x] rmr fixed now?
- [x] calculate correct RMR averages with Days factor column (which misses currently).
- [x] should TotalEnergyExpenditure be the total really or the average over the number of full days? 
- [x] make metadata ticked as default, if metadata avialable, override timeline for daynight automatically?
- [x] RMR does fail without metadata, rename columns
- [x] trim and select experimental days, does ot work when more than one data file provided (metadata does not matter)

initial bare-bone release: v0.1.0
