### ISSUE TITLE
Roadmap v0.4.0

### ISSUE THREAD

**Issue by stephanmg** [stephanmg/calorimetry#70]
before release v0.4.0:
- [x] Document actual `.R` code with RTD,  push to local gh_pages branch until repository is public
- [ ] Betatester für App (Ronja, Tabea: UB) (Karthik, Janina, Sabrina, Jennifer: UKE), Johanna/Martin (TUM) und Uni Graz überzeugen 

code:
- [x] code review and speed up computations
- [ ] code review: cleanup and refactoring
