### ISSUE TITLE
Roadmap v0.5.0

### ISSUE THREAD

**Issue by stephanmg** [stephanmg/calorimetry#76]
- [ ] correct for measurement interval length might change during long experiments... 14 days. different time_diffs. n
- [ ] tse header must be valid, e.g. Weight with . instead of , and if Genotype etc is used in metadata sheet, it has to be matching the tse header (no other groups like cntrl in tse header if in metadata sheet is cntl and wt for instance), otherwise do not export tse header from phenomaster at all...
- [ ] relax tse header needs to be valid, example by Ronja, argument of length 0 error
- [ ] support Phenomaster v8 Spaltenformat statt Zeilenformat
- [ ] imputation bzw. interpolation von daten wenn measurement interval sich ändert, ist das ein problem? 
- [ ] add outlier removal methods to all panels (from Raw panel)
- [ ] Johanna: Add Load/Save button in Desktop app for storing data -> store an R data frame and restore the work
- [ ] Johanna: less reactive when selecting things we trigger calculation: add buttons for this: use button and eventreactive in 
- [ ] support promethion/sable column format 

completion of tasks will trigger release v0.5.0
