### ISSUE TITLE
Roadmap v0.6.0

### ISSUE THREAD

**Issue by stephanmg** [stephanmg/calorimetry#83]
- [ ] explicit selection of calendrical dates (preprocessing) is a different feature and requires changes to utility functions zeitgeber_time -> see util.R 
- [ ] address todos in body_composition.R - mostly support 3-way, 4-way ANOVA directly, 5-way via estimated marginal means (interaction plots as in ANCOVA panels for measurements, + summary tables)
- [ ] Find best LME model via model selection? shiny - ask Chat
- [ ] COSMED features for Turku
- [ ] SABLE features for UKE

completion of disucssion will trigger release v0.6.0
