### ISSUE TITLE
Roadmap v0.7.0

### ISSUE THREAD

**Issue by stephanmg** [stephanmg/calorimetry#86]
General:
- [ ] Measurement interval length might change during very long experiments... 14 days, resulting in different `time_diffs` for the interval length during energy expenditure calculation - check if Data imputation and Interpolation effects this negatively.
- [ ] Allow selection of calendrical days in addition to full day selection with zeitgeber time or regular time

Data formats:
- [ ] Support of Phenomaster v8 column-based format
- [ ] Support Promethion/Sable column-based format 

Data curation:
- [ ] Add outlier removal and interpolation methods to all panels (see example in Raw panel)

Usability of app:
- [ ] Add Load/Save button in Desktop app for storing data -> store an R data frame and restore the work
- [ ] Johanna: less reactive in general would be preferable when selecting data: use a button to trigger calculation
