### ISSUE TITLE
Roadmap v0.5.0

### ISSUE THREAD

**Issue by stephanmg** [stephanmg/calorimetry#87]
v0.5.0:

- [x] Add packages from calobox, sg_filter and solr_enhancmeent to CI after merging
- [x] Revise interpolation to time grid, guard against duplicated values (see TODO) which otherwise fails `approx(...)`.
- [ ] Add metabolic activity (tiled plots and  contour plots from review)
- [ ] exclude measurements by box, time and date (use Metadata Sheet, timeline dependent changes)
- [ ] select days for individual cohorts, not globally for all cohorts.

Usability of app:
- [x] #105
- [x] #104
